HAI  
   WAZZUP
   I HAS A var1
   BUHBYE
   VISIBLE "Hello World"
   VISIBLE SUM OF DIFF OF 3 AN 5.5 AN DIFF OF 12 AN 13
   VISIBLE PRODUKT OF -5 AN SUM OF 5 AN 5
   VISIBLE QUOSHUNT OF 5 AN 2.5
   VISIBLE BOTH SAEM 3 AN 3
   VISIBLE BOTH SAEM 2 AN 3
   VISIBLE DIFFRINT 3 AN 3
   VISIBLE DIFFRINT 2 AN 3
   VISIBLE EITHER OF WIN AND FAIL
   VISIBLE BOTH OF WIN AND FAIL
   VISIBLE NOT WIN
   VISIBLE WON OF FAIL AND FAIL
   VISIBLE BOTH OF FAIL AND FAIL
   VISIBLE SMOOSH "test" AN "123"
KTHXBYE